"""Video Stream Tester.

This script is for using a video video stream from your webcam
as the input to a model.
"""
import cv2

from lns_common.model import Model

CLAHE = cv2.createCLAHE(clipLimit=4.0, tileGridSize=(8, 8))


def save_bounding_box_video(model: Model, vid_path: str, wid: int, hgt: int):
    '''Saves video overlayed with bounding boxes generated by model'''

    cap = cv2.VideoCapture(vid_path)
    writer = cv2.VideoWriter("bb_output.mp4", cv2.VideoWriter_fourcc(*"MJPG"),
                             30, (wid, hgt))

    vid_end = 0
    while ((writer.isOpened()) and (not vid_end)):
        _, img = cap.read()
        if _:
            detected_list = model.predict(img)
            for obj in detected_list:
                label = obj.predicted_classes[0]

                if label == "Red":
                    color = (255, 0, 0)
                elif label == "Yellow":
                    color = (0, 255, 0)
                elif label == "Green":
                    color = (0, 255, 0)
                else:
                    color = (0,0,0)

                b = obj.bounding_box
                cv2.rectangle(
                    img,
                    (b.left, b.top),
                    (b.left + b.width, b.top + b.height),
                    (255,0,0),
                    2,
                )
                cv2.putText(
                    img,
                    label,
                    (b.left, b.height),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.8,
                    (0, 255, 255),
                    thickness=2,
                    lineType=cv2.LINE_AA,
                )
            writer.write(img)
        else:
            vid_end = 1

    writer.release()
    cv2.destroyAllWindows()