"""Haar model representation.

This module contains the prediction model that will be generated by the Haar
training.
"""
from typing import List

import numpy as np

from haar.common import config
from haar.common.model import Model, PredictedObject2D

cv2 = config.get_opencv_bindings()


class HaarModel(Model):
    """Bounding-box prediction model utilizing Haar cascades."""

    __cascade: cv2.CascadeClassifier

    def __init__(self, cascade: cv2.CascadeClassifier) -> None:
        """Initialize a Haar cascade model with the given <cascade>."""
        self.__cascade = cascade

    def predict(self, image: np.ndarray) -> List[PredictedObject2D]:
        """Predict the required bounding boxes on the given <image>."""
        # TODO: implement
        raise NotImplementedError
