"""SVM representation.

This module will contains the prediction model that will be generated by the training of the Support Vector Machine
"""

from sklearn.svm import SVC
import numpy as np

from lns.common.model import Model
from lns.common.structs import Object2D, Bounds2D
from typing import List


class SVMModel(Model):
    """Class prediction using Support Vector Machine."""

    def __init__(self) -> None:
        """Initialize the model."""
        self.__clf = SVC(kernel='linear')

    def predict(self, image: np.ndarray) -> List[Object2D]:
        """Return integer as prediction of class."""
        im = image.reshape(64, 64)
        im = im.flatten()
        pred = self.__clf.predict(im)
        bound = Bounds2D(0, 0, 0, 0)

        return [Object2D(bound, pred, 1)]
