"""YOLOv3 model representation.

This module contains the prediction model that will be generated by the Haar training.
"""
from typing import List

import numpy as np  # type: ignore

from lns.common.model import Model
from lns.common.structs import Object2D


class YoloModel(Model):
    """Detection model utilizing YOLOv3."""

    def __init__(self, config_file: str, weights_file: str) -> None:
        """Initialize a YOLOv3 model."""
        raise NotImplementedError

    def predict(self, image: np.ndarray) -> List[Object2D]:
        """Predict the required bounding boxes on the given <image>."""
        raise NotImplementedError
