"""YOLOv3 model representation.

This module contains the prediction model that will be generated by the Haar training.
"""
from typing import Optional, List

import numpy as np       # type: ignore
import tensorflow as tf  # type: ignore

from lns.common.model import Model
from lns.common.structs import Object2D
from lns.yolo.settings import YoloSettings


class YoloModel(Model):
    """Detection model utilizing YOLOv3."""

    def __init__(self, weights_file: str, anchors_file: str, settings: Optional[YoloSettings] = None) -> None:
        """Initialize a YOLOv3 model."""
        if not settings:
            settings = YoloSettings()

        from lns.yolo._lib.utils.nms_utils import gpu_nms
        from lns.yolo._lib.model import yolov3
        from lns.yolo._lib import args

        args.restore_path = weights_file
        args.anchor_path = anchors_file
        for field, setting in zip(settings._fields, settings):
            setattr(args, field, setting)
        args.optimizer_name = settings.optimizer_name.value
        args.lr_type = settings.lr_type.value
        args.init_inference()

        self._is_training = tf.placeholder(dtype=tf.bool, name="phase_train")
        self._pred_boxes_flag = tf.placeholder(tf.float32, [1, None, None])
        self._pred_scores_flag = tf.placeholder(tf.float32, [1, None, None])
        self._image = tf.placeholder(tf.float32, [1, args.img_size[1], args.img_size[0], 3])
        self._gpu_nms_op = gpu_nms(self._pred_boxes_flag, self._pred_scores_flag,
                                   args.class_num, args.nms_topk, args.score_threshold, args.nms_threshold)

        yolo_model = yolov3(args.class_num, args.anchors)
        with tf.variable_scope('yolov3'):
            pred_feature_maps = yolo_model.forward(self._image, is_training=self._is_training)
        self._y_pred = yolo_model.predict(pred_feature_maps)

        self._session = tf.Session()
        self._session.run([tf.global_variables_initializer()])
        tf.train.Saver().restore(self._session, args.restore_path)

    def predict(self, image: np.ndarray) -> List[Object2D]:
        """Predict the required bounding boxes on the given <image>."""
        from lns.yolo._lib.utils.eval_utils import get_preds_gpu

        y_pred = self._session.run([self._y_pred], feed_dict={self._is_training: False, self._image: image})
        pred_content = get_preds_gpu(self._session, self._gpu_nms_op, self._pred_boxes_flag,
                                     self._pred_scores_flag, [0], y_pred)
        print(pred_content)
